//$("a[download]").css("border", "1px solid red"); //Полный атрибут
//$('a[href="http://ya.ru"]').css("border", "1px solid green"); //Полное соответствие
//$('a[href!="http://ya.ru"]').css("border", "1px solid green"); //Полное несоответствие
//$('a[href^="http"]').css("border", "1px solid green"); //Начинается с ...
//$('a[href$=".com"]').css("border", "1px solid green"); //Заканчивается на ...
//$('a[href*="ya"]').css("border", "1px solid green"); //Содержит ...
//$('a[data-target|="main"]').css("border", "1px solid green"); //Имеет префикс ...
//$("a[href][download]").css("border", "1px solid green"); //Имеет одновременно несколько атрибутов ...
